//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScrumCase.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int id { get; set; }
        public string name { get; set; }
        public int statusID { get; set; }
        public int priority { get; set; }
        public System.DateTime estimatedHours { get; set; }
        public string description { get; set; }
        public int PBLItemID { get; set; }
        public Nullable<int> personID { get; set; }
        public Nullable<System.DateTime> assignmentDate { get; set; }
        public Nullable<System.DateTime> completionDate { get; set; }
    
        public virtual PBLItem PBLItem { get; set; }
        public virtual Person Person { get; set; }
        public virtual Status Status { get; set; }
    }
}
